---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
  -
    if: tag =~ ^v\d
    name: deploy
matrix:
  fast_finish: true
  include:
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-8 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-9 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1604 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args: --with system_tests
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1804 BEAKER_TESTMODE=apply
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      stage: acceptance
      sudo: required
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      env: DEPLOY_TO_FORGE=yes
      stage: deploy
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: trepasi
  password:
    secure: "kz1gJ3sbwH9vyhmfqgW7KG8K2L1Zx+bYuOkCom68ljr2UQ5Wbpaomvkd7lAiJr1tfrDxJ9NacXTIfhpYmwD+bssWhTNrHHYRNFCAzc5aSJQLxZMEQrwz/KjQjj8ckSaSX9kEKAUYx61OezD78hHPb5mqRhfFkhl4S1fUaZ3J1a8yzybrFv3TGNalb1GboCWCP6kTUguBOVCMeylM1eIDDYNPKvYYzZVEQRqgAPRsxQJUn+nr2sglMyLLuO9S1ALFDRXWbxxfyCf5e/c5Oqfsed2UMyB8vuuM2Vpz30VPsQQjWdMaM1oKC5BhIMf+W5UBKSn6mx2KT4hiqw5KB05V4grQ07ibYiJXW/rwb7I6Bk+bqaAy6cd2gZiuOroqLgy/qPj5viwiBnPts+8e+Edj91aVOj+sSFaVD/ZAFYKVeeDDt28Fag8Dj+xVBT/SvpaQHOXnojksvqixeLMbehdfgvKwg2qpS1h1/qgi8pVuiCywFtnaPuw2j/RcAhduj5JctyWFkNT09Vqxp6edTpXKBoXi6YR+NWSEkoOZ3+AWne4ZbRaCndnTU2fM5Nfz/psytb7E2S20ESdItb4j0I7cKo70YjknGfGweScbHdnPtLu88hFxaTfSUUY1mf1e0Dc7q794IwzrPc3cIVwMX60f/b05PB88i444nEn2xE5R0Bw="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
